In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [4]:
array = np.random.rand(3, 4)
print(array)

[[2.82902032e-01 3.03277946e-01 8.37869965e-01 8.77551332e-01]
 [2.88290053e-01 3.86432383e-01 9.83204952e-02 2.35713740e-01]
 [3.99539067e-01 3.75124511e-04 5.55370968e-01 2.53761411e-01]]


In [5]:
mul = np.dot(array1, array2)
print(mul)

[[ 81 -33]
 [ 79 -39]]


In [8]:
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[81, -33], [79, -39]]


In [9]:
mean = np.mean(array1)
print(mean)

5.333333333333333


In [12]:
main_data = pd.read_csv("/content/drive/MyDrive/ML_Lab1/mtcars.csv")

In [13]:
del main_data['model']
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]


In [16]:
alist = [1, 2, 3, 4, 5] 
narray = np.array([1, 2, 3, 4])

print(alist)
print(narray)
print(type(alist))
print(type(narray))
#Difference betweeen the arrays

print(narray + narray)
print(alist + alist)

print(narray * 3)
print(alist * 3)

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [17]:
npmatrix1 = np.array([narray, narray, narray])
npmatrix2 = np.array([alist, alist, alist]) 
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) 
print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [18]:
okmatrix = np.array([[1, 2], [3, 4]]) 
print(okmatrix) 
print(okmatrix * 2) 

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [19]:
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix) 
print(badmatrix * 2) 

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [20]:
#Operation on matrices
result = okmatrix * 2 + 1
print(result)
result1 = okmatrix + okmatrix
print(result1)
result2 = okmatrix - okmatrix
print(result2)
result = okmatrix * okmatrix 
print(result)

[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]


In [21]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) 
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [22]:
nparray = np.array([1, 2, 3, 4]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [23]:
nparray = np.array([[1, 2, 3, 4]]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


In [24]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)
nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)
print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [25]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(nparray2, axis=0) 
normByRows = np.linalg.norm(nparray2, axis=1) 
print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [26]:
nparray1 = np.array([0, 1, 2, 3]) 
nparray2 = np.array([4, 5, 6, 7]) 
flavor1 = np.dot(nparray1, nparray2)
print(flavor1)
flavor2 = np.sum(nparray1 * nparray2)
print(flavor2)
flavor3 = nparray1 @ nparray2 
print(flavor3)
flavor4 = 0
for a, b in zip(nparray1, nparray2):
  flavor4 += a * b
print(flavor4)

38
38
38
38


In [27]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4])) 
norm2 = np.dot([1, 2], [3, 4]) 
print(norm1, '=', norm2 )

11 = 11


In [34]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
sumByCols = np.sum(nparray2, axis = 0)
sumByRows = np.sum(nparray2, axis = 1)
print("Sum Columns : ", sumByCols)
print("Sum Rows : ", sumByRows)

Sum Columns :  [ 6 -6]
Sum Rows :  [0 0 0]


In [33]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
mean = np.mean(nparray2)
meanByCols = np.mean(nparray2, axis = 0)
meanByRows = np.mean(nparray2, axis = 1)
print("Matrix mean : ", mean)
print("Mean Columns : ", meanByCols)
print("Mean Rows : ", meanByRows)

Matrix mean :  0.0
Mean Columns :  [ 2. -2.]
Mean Rows :  [0. 0. 0.]


In [35]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
nparrayCentered = nparray2 - np.mean(nparray2, axis = 0)
print("Main matrix : ", nparray2)
print("Centered by columss matrix : ", nparrayCentered)
print("New mean by columns : ", nparrayCentered.mean(axis = 0))

Main matrix :  [[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
Centered by columss matrix :  [[-1.  1.]
 [ 0.  0.]
 [ 1. -1.]]
New mean by columns :  [0. 0.]


In [36]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]])
nparrayCentered = nparray2.T - np.mean(nparray2, axis = 1)
nparrayCentered = nparrayCentered.T
print("Main matrix : {nparray2}")
print("Centered by Columns : ", nparrayCentered)
print("New mean by Rows : ", nparrayCentered.mean(axis = 1))

Main matrix : {nparray2}
Centered by Columns :  [[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by Rows :  [0. 0. 0.]
