In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

dataset1 = pd.read_csv("/content/drive/MyDrive/ML_Lab1/ML_Lab3/Dataset1.csv")

In [5]:
#Preprocessing
le = preprocessing.LabelEncoder()

dummy_outlook = pd.get_dummies(dataset1['Outlook'])
dataset1 = dataset1.drop(['Outlook'],axis=1)
dataset1 = pd.concat([dummy_outlook,dataset1],axis=1)

dummy_wind = pd.get_dummies(dataset1['Wind'])
dataset1 = dataset1.drop(['Wind'],axis=1)
dataset1 = pd.concat([dummy_wind,dataset1],axis=1)

dataset1['Temp'] = le.fit_transform(dataset1['Temp'])
dataset1['Humidity'] = le.fit_transform(dataset1['Humidity'])
dataset1['Play'] = le.fit_transform(dataset1['Play'])


print(dataset1)

    F  T  O  R  S  Temp  Humidity  Play
0   1  0  0  1  0     1         2     0
1   0  1  0  1  0     1         0     0
2   1  0  1  0  0     1         2     1
3   1  0  0  0  1     2         2     1
4   1  0  0  0  1     0         2     1
5   0  1  0  0  1     0         1     0
6   0  1  1  0  0     0         2     1
7   1  0  0  1  0     2         2     0
8   1  0  0  1  0     0         1     1
9   1  0  0  0  1     2         0     1
10  0  1  0  1  0     2         0     1
11  0  1  1  0  0     2         1     1
12  1  0  1  0  0     1         2     1
13  0  1  0  0  1     2         2     0


In [7]:
X = dataset1.iloc[:,:7].values
Y = dataset1.iloc[:,7].values
print(X)
print(Y)

[[1 0 0 1 0 1 2]
 [0 1 0 1 0 1 0]
 [1 0 1 0 0 1 2]
 [1 0 0 0 1 2 2]
 [1 0 0 0 1 0 2]
 [0 1 0 0 1 0 1]
 [0 1 1 0 0 0 2]
 [1 0 0 1 0 2 2]
 [1 0 0 1 0 0 1]
 [1 0 0 0 1 2 0]
 [0 1 0 1 0 2 0]
 [0 1 1 0 0 2 1]
 [1 0 1 0 0 1 2]
 [0 1 0 0 1 2 2]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 64)

In [13]:
model=MultinomialNB()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
print(Y_test)
print(Y_pred)

[1 1 1]
[0 1 1]


In [14]:
from sklearn import metrics

print(f"Accuracy is :- {metrics.accuracy_score(Y_test, Y_pred)}")

# print precision and recall
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)

print(f"precision :- {precision}")
print(f"recall :- {recall}")

Accuracy is :- 0.6666666666666666
precision :- 1.0
recall :- 0.6666666666666666
